### ISSUE TITLE
Reflections on the Pyramid Approach

### ISSUE THREAD

**Issue by t676290894** [zzzzxxxx111/SLslam#13]
Hello, thank you for your contribution. ORB-SLAM3 uses the pyramid hierarchy and grayscale centroid method to ensure the scale and rotation invariance of feature points. However, SL-SLAM does not seem to address this aspect. I would like to inquire about relevant information.

**Comment by zzzzxxxx111** [comment]
Thank you very much for your attention. The learn-based feature points are not very sensitive to scale and rotation changes due to the large amount of data training. Therefore, no additional feature point preprocessing method is adopted in this slam system.

**Comment by t676290894** [comment]
Thank you for answering my question. I look forward to your article being accepted.
